# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.17 on 2026-10-06 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseState",
            fields=[
                (
                    "case_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("fingerprint", models.CharField(max_length=64, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "assessment_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField()),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("snapshot_json", models.TextField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.casestate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "operation_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("case_revision", models.PositiveIntegerField()),
                ("decision", models.CharField(max_length=20)),
                ("note", models.CharField(max_length=2000)),
                ("officer_name", models.CharField(max_length=301)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.assessment",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("case", "version"), name="assessment_case_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="assessment_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ["approved", "changes_requested"])),
                name="review_valid_decision",
            ),
        ),
    ]
