# Generated by Django 5.2.17 on 2026-10-06 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0002_immutable_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "operation_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("case_revision", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField()),
                ("request_json", models.TextField()),
                ("snapshot_json", models.TextField()),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.assessment",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "version"),
                        name="draft_assessment_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="draft_positive_version",
                    ),
                ],
            },
        ),
    ]
