# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.17 on 2026-10-06 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0004_immutable_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftReview",
            fields=[
                (
                    "operation_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("case_revision", models.PositiveIntegerField()),
                ("decision", models.CharField(max_length=20)),
                ("note", models.CharField(max_length=2000)),
                ("officer_name", models.CharField(max_length=301)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="persistence.draft",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("decision__in", ["approved", "changes_requested"])),
                        name="draft_review_valid_decision",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER immutable_draft_review BEFORE UPDATE OR DELETE ON persistence_draftreview
                FOR EACH STATEMENT EXECUTE FUNCTION farmcredit_immutable_draft();
            """,
            reverse_sql="DROP TRIGGER immutable_draft_review ON persistence_draftreview;",
        ),
    ]
