# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.17 on 2026-10-06 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0005_draftreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("run_id", models.UUIDField(primary_key=True, serialize=False)),
                ("scope_json", models.TextField()),
                ("case_revision", models.PositiveIntegerField()),
                ("status", models.CharField(default="active", max_length=20)),
                ("reason", models.CharField(blank=True, max_length=256)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.assessment",
                    ),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.draft",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("sequence", models.PositiveIntegerField()),
                ("tool", models.CharField(max_length=40)),
                ("arguments_json", models.TextField()),
                ("status", models.CharField(default="running", max_length=20)),
                ("result_json", models.TextField(null=True)),
                ("error", models.CharField(blank=True, max_length=256)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="persistence.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "completed", "incomplete"])),
                name="run_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="toolcall",
            constraint=models.UniqueConstraint(
                fields=("run", "operation_id"), name="run_call_operation"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolcall",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="run_call_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolcall",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "succeeded", "failed"])),
                name="call_valid_status",
            ),
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION farmcredit_run_transition() RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Run history is immutable' USING ERRCODE = '23000';
                END IF;
                IF OLD.status <> 'active'
                    OR NEW.status NOT IN ('completed', 'incomplete')
                    OR NEW.finished_at IS NULL
                    OR (to_jsonb(NEW) - ARRAY['status','reason','finished_at','draft_id'])
                        IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status','reason','finished_at','draft_id'])
                    OR (NEW.status = 'completed' AND NEW.draft_id IS NULL)
                    OR (NEW.status = 'incomplete' AND NEW.draft_id IS NOT NULL) THEN
                    RAISE EXCEPTION 'Run binding and final state are immutable' USING ERRCODE = '23000';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER run_transition BEFORE UPDATE OR DELETE ON persistence_agentrun
                FOR EACH ROW EXECUTE FUNCTION farmcredit_run_transition();
            CREATE FUNCTION farmcredit_call_transition() RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Tool history is immutable' USING ERRCODE = '23000';
                END IF;
                IF OLD.status <> 'running'
                    OR NEW.status NOT IN ('succeeded', 'failed')
                    OR NEW.finished_at IS NULL
                    OR (to_jsonb(NEW) - ARRAY['status','error','result_json','finished_at'])
                        IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status','error','result_json','finished_at']) THEN
                    RAISE EXCEPTION 'Tool arguments and outcomes are immutable' USING ERRCODE = '23000';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER call_transition BEFORE UPDATE OR DELETE ON persistence_toolcall
                FOR EACH ROW EXECUTE FUNCTION farmcredit_call_transition();
            """,
            reverse_sql="""
            DROP TRIGGER call_transition ON persistence_toolcall;
            DROP FUNCTION farmcredit_call_transition();
            DROP TRIGGER run_transition ON persistence_agentrun;
            DROP FUNCTION farmcredit_run_transition();
            """,
        ),
    ]
