# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.17 on 2026-10-06 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0006_agent_runs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="persistence.assessment",
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="persistence.assessment",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationVersion",
            fields=[
                ("application_id", models.UUIDField(primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("snapshot_json", models.TextField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persistence.casestate",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="persistence.applicationversion",
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="persistence.applicationversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("application__isnull", True), ("assessment__isnull", False)),
                    models.Q(("application__isnull", False), ("assessment__isnull", True)),
                    _connector="OR",
                ),
                name="agentrun_one_input_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.UniqueConstraint(
                fields=("application", "version"), name="draft_application_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("application__isnull", True), ("assessment__isnull", False)),
                    models.Q(("application__isnull", False), ("assessment__isnull", True)),
                    _connector="OR",
                ),
                name="draft_one_input_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationversion",
            constraint=models.UniqueConstraint(
                fields=("case", "version"), name="application_case_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="application_positive_version",
            ),
        ),
        migrations.RunSQL(
            "CREATE TRIGGER immutable_application BEFORE UPDATE OR DELETE ON persistence_applicationversion FOR EACH STATEMENT EXECUTE FUNCTION farmcredit_immutable_audit();",
            "DROP TRIGGER immutable_application ON persistence_applicationversion;",
        ),
    ]
