# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.17 on 2026-10-06 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0007_application_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="execution_kind",
            field=models.CharField(default="internal_tools", max_length=24),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="model",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="InvestigationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("payload_json", models.TextField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="persistence.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="RunEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("snapshot_json", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="persistence.agentrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "category"), name="run_evidence_category"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER immutable_investigation_event BEFORE UPDATE OR DELETE
            ON persistence_investigationevent FOR EACH STATEMENT
            EXECUTE FUNCTION farmcredit_immutable_audit();
            CREATE TRIGGER immutable_run_evidence BEFORE UPDATE OR DELETE
            ON persistence_runevidence FOR EACH STATEMENT
            EXECUTE FUNCTION farmcredit_immutable_audit();
            """,
            reverse_sql="""
            DROP TRIGGER immutable_investigation_event ON persistence_investigationevent;
            DROP TRIGGER immutable_run_evidence ON persistence_runevidence;
            """,
        ),
    ]
